name: fb2_parse
description: Flutter package for parsing fb2 files. Returns html content
version: 1.0.1

repository: https://github.com/kuthon/fb2_parse
homepage: https://github.com/kuthon/fb2_parse

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:

  flutter:
    sdk: flutter
  xml: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
